### ISSUE TITLE
Problem sa kompilacijom

### ISSUE THREAD

**Issue by DenisAlicic** [mrdakj/tiger#1]
Ljudi,

Ja kad pokusam da kompajliram izbaci mi sledecu gresku:

./symbol_table.hpp:8:10: fatal error: 'optional' file not found
#include<optional>
1 error generated.

E sad,ja sam trazio po netu i pise kao da mogu da stavim #include<experimental/optional>,ali ja ne zelim da diram kod u tom smislu. Pomoc?

**Comment by mrdakj** [comment]
hey hey,

ja ga prevodim ovako:
g++ -std=c++17 symbol_table.cpp -c
g++ -std=c++17 main.cpp symbol_table.o

probaj da li ti ovako radi

нед, 5. авг 2018. у 21:25 Denis Alicic <notifications@github.com> је
написао/ла:

**Comment by DenisAlicic** [comment]
U redu je sad,

BIlo je do verzije kompajlera i standardne biblioteke. Mogu li da promenim Makefile da stavim samo g++ umesto clang++?

**Comment by mrdakj** [comment]
Ma naravno, menjaj slobodno sta god mislis da treba

нед, 5. авг 2018. у 23:59 Denis Alicic <notifications@github.com> је
написао/ла:
